Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/LineLength:
  Max: 160

Style/IfUnlessModifier:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 8

AllCops:
  TargetRubyVersion: 2.2
